### ISSUE TITLE
What does "trans" represent?

### ISSUE THREAD

**Issue by yizhexu** [stefangroha/SurvNODE#1]
Can you explain what "trans" variable is and how was is generated? 

It seems like coxed package was used to create [this](https://github.com/stefangroha/SurvNODE/blob/main/Data/multistate_trainval.csv) dataset. How did you create the "trans" variable? What does it represent? Apologies if I overlooked your description in the paper. 

Can you also explain what "status" mean in the dataset? Is it the final status (live or death), or it is the status at the time of observation?

**Comment by stefangroha** [comment]
The "trans" variable just numbers the transitions in a multi-state model. So while in the survival case it's all the same transition, in the illness death model there are three possible transitions, which are just numbered 1 to 3. This is in line with what msprep from the mstate package generates (long format), however with the caveat that msprep generates additional lines in the case of competing transitions, which have to be removed to be used with survnode.

The variable status signifies if the transition is observed or not, so the status at time of observation, this does not necessarily mean alive or dead, as a patient can be censored at any time in the multi-state graph.

This code was not intended for code release yet, we will update the code and add some documentation soon, sorry for the preliminary state.

**Comment by yizhexu** [comment]
Thank you, I will consult mstate msprep to understand "trans" variable. 

And thank you for making the preliminary research code public. I understand the limitations. This accelerated my understanding of your paper.
